version: '3.5'

services:

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    ports:
      - 9042:9042
    networks:
      - sparknet

#  runner:
#    image: mm:latest
#    hostname: runner
#    depends_on:
#      - cassandra
#    ports:
#      - 4040:4040
#    networks:
#      - sparknet
#    volumes:
#      - /Users/ms250139/Sources/courses/DE/yelp_dataset:/data

  master:
    image: mshtelma/spark-base:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    ports:
      - 6066:6066
      - 7077:7077
      - 8080:8080
    networks:
      - sparknet
    volumes:
      - /tmp/yelp_dataset:/data

  worker:
    image: mshtelma/spark-base:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_PUBLIC_DNS: ${EXTERNAL_IP}
    deploy:
      replicas: 3
    depends_on:
      - master
    ports:
      - 8081:8081
    networks:
      - sparknet
    volumes:
      - /tmp/yelp_dataset:/data

networks:
  sparknet:
